[package]
name = "generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
chrono = "0.4.23"
graphql_client = { version = "0.12.0", features = ["reqwest"] }
human_bytes = "0.4.1"
itertools = "0.10.5"
lastfm-rs = "0.5.0"
once_cell = "1.17.0"
reqwest = "0.11.14"
rss = "2.0.2"
serde = "1.0.152"
serde_derive = "1.0.152"
tinytemplate = "1.2.1"
tokio = { version = "1.24.2", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
urlencoding = "2.1.2"

[features]
