[package]
name = "generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
chrono = "0.4.19"
graphql_client = { version = "0.10.0", features = ["reqwest"] }
human_bytes = "0.3.1"
itertools = "0.10.3"
lastfm-rs = "0.5.0"
once_cell = "1.10.0"
reqwest = "0.11.10"
rss = "2.0.0"
serde = "1.0.136"
serde_derive = "1.0.136"
tinytemplate = "1.2.1"
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.32"
tracing-subscriber = "0.3.9"

[features]
