name: Regenerate profile README.md

on:
  push:
    branches:
      - master
  schedule:
    - cron: "33 4 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    environment: "Profile regeneration"
    steps:
      - uses: actions/checkout@v3
      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Cargo build
        run: |
          cargo build
      - name: Configure Git
        run: |
          git config --global user.email "murderbot@example.com"
          git config --global user.name "Murderbot"
      - name: Run generator
        run: |
          set -e
          set -x
          RUST_LOG=debug GITHUB_TOKEN=${{ github.token }} LAST_FM_API_KEY=${{ secrets.LAST_FM_API_KEY }} ./target/debug/generator
      - name: Commit and push if changed
        run: |
          if [[ `git status --porcelain` ]]; then
              git commit -a -m 'Regenerated profile README.md'
              git push
          fi
