name: Regenerate profile README.md

on:
  push:
    branches:
      - master
  schedule:
    - cron: "33 4 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v1
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable
          override: true
      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: Configure Git
        run: |
          git config --global user.email "murderbot@example.com"
          git config --global user.name "Murderbot"
      - name: Commit and push if changed
        run: |
          set -e
          set -x
          RUST_LOG=info GITHUB_TOKEN=${{ github.token }} ./target/debug/generator
          if [[ `git status --porcelain` ]]; then
              git commit -a -m 'Regenerated profile README.md'
              git push
          fi
